import axiosClient from './axiosClient'
export const getSessions = () => axiosClient.get('/proofing').then(r => r.data)
export const createSession = (data) => axiosClient.post('/proofing', data).then(r => r.data)
export const getSession = (id) => axiosClient.get(`/proofing/${id}`).then(r => r.data)
export const updateSession = (id, data) => axiosClient.put(`/proofing/${id}`, data).then(r => r.data)
export const deleteSession = (id) => axiosClient.delete(`/proofing/${id}`).then(r => r.data)
export const sendInvite = (id) => axiosClient.post(`/proofing/${id}/send-invite`).then(r => r.data)
export const getClientSession = (token) => axiosClient.get(`/proofing/session/${token}`).then(r => r.data)
export const submitSelection = (token, data) => axiosClient.post(`/proofing/session/${token}/select`, data).then(r => r.data)
export const submitComment = (token, data) => axiosClient.post(`/proofing/session/${token}/comment`, data).then(r => r.data)
export const getSelectionSummary = (token) => axiosClient.get(`/proofing/session/${token}/summary`).then(r => r.data)
